- hosts: all
  roles:
    - role: system/config-system
      tags: role-config-system
    - role: system/secure-system
      tags: role-secure-system
    - role: docker
      tags: role-docker
    - role: system/openshift
      tags: role-openshift

- hosts: masters
  environment: "{{ kube_config_path }}"
  roles:
    - role: kubernetes/masters
      tags: role-kubernetes-masters
    - role: scaleway-csi
      tags: role-scaleway-csi
    - role: gitlab
      tags: role-gitlab
    - role: monitoring/prometheus
      tags: role-monitoring-prometheus
    - role: monitoring/prometheus-kafka
      tags: role-monitoring-prometheus-kafka
    - role: monitoring/kube-state-metrics
      tags: role-monitoring-kube-state-metrics
    - role: monitoring/grafana
      tags: role-monitoring-grafana
    - role: networking/nginx-ingress
      tags: role-networking-nginx-ingress
    - role: networking/cert-manager
      tags: role-networking-cert-manager
    - role: security/oauth2-proxy
      tags: role-security-oauth2-proxy
    - role: kafka
      tags: role-kafka
    - role: database/postgres
      tags: role-postgres
    - role: database/postgres-cluster/postgres-operator
      tags: role-postgres-cluster-operator
    - role: database/postgres-cluster/operator-ui
      tags: role-postgres-cluster-ui
    - role: database/mongodb
      tags: role-mongodb
    - role: database/redis
      tags: role-redis
    - role: discord/omnibot
      tags: role-omnibot
    - role: discord/discord-rss
      tags: role-discord-rss
    - role: blog
      tags: role-blog

- hosts: workers
  roles:
    - role: kubernetes/workers
      tags: role-kubernetes-workers
