---
apiVersion: v1
kind: Secret
metadata:
  name: scaleway-secret
  namespace: kube-system
type: Opaque
stringData:
  SCW_ACCESS_KEY: "{{ scaleway.access_key }}"
  SCW_SECRET_KEY: "{{ scaleway.secret_key }}"
  SCW_DEFAULT_ORGANIZATION_ID: "{{ scaleway.organization_id }}"
  SCW_DEFAULT_ZONE: "{{ scaleway.default_zone }}"