- name: Create datasource config
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'datasource-config.j2') }}"

- name: Create deployment
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'deployment.j2') }}"

- name: Create service
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'service.j2') }}"

- name: Create ingress for ingress-nginx
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'ingress.j2') }}"