- name: Create namespace
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'namespace.j2') }}"

- name: Create configmap
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'configmap.j2') }}"

- name: Create rbac
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'rbac.j2') }}"

- name: Create deployment
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'deployment.j2') }}"

- name: Create limitrange
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'limitrange.j2') }}"

- name: Create service
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'service.j2') }}"

- name: Enable ufw ports for HTTP
  become: yes
  ufw:
    rule: allow
    port: "{{ nodeport_http }}"
    proto: tcp

- name: Enable ufw ports for HTTPS
  become: yes
  ufw:
    rule: allow
    port: "{{ nodeport_https }}"
    proto: tcp