- name: Create namespace
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'namespace.yml') }}"

- name: Create secrets
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'secrets.yml') }}"

- name: Create configmap
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'configmap.yml') }}"


- name: Create deployment
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'deployment.yml') }}"

- name: Create service
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'service.yml') }}"

- name: Create ingress
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'ingress.yml') }}"
