apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: "{{ oauth.namespace }}"
type: Opaque
data:
  cookie-secret: "{{ oauth_secrets.cookie_secret | b64encode }}"
  client-id: "{{ oauth_secrets.client_id | b64encode }}"
  client-secret: "{{ oauth_secrets.client_secret | b64encode }}"