apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: "{{ postgres_namespace }}"
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30001