apiVersion: apps/v1  #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: postgres
  namespace: "{{ postgres_namespace }}"
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "{{ postgres_secrets.user }}"
          - name: POSTGRES_PASSWORD
            value: "{{ postgres_secrets.password }}"
          - name: POSTGRES_DB
            value: "{{ postgres_secrets.db }}"
          - name: PGDATA
            value: "/var/lib/postgresql/data/pgdata"
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "scw-bssd"
      resources:
        requests:
          storage: 40Gi