apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "postgres-operator-ui"
  namespace: "postgres"
  labels:
    name: "postgres-operator-ui"
    team: "acid"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "postgres-operator-ui"
  template:
    metadata:
      labels:
        name: "postgres-operator-ui"
        team: "acid"
    spec:
      serviceAccountName: postgres-operator-ui
      containers:
        - name: "service"
          image: registry.opensource.zalan.do/acid/postgres-operator-ui:v1.5.0-dirty
          ports:
            - containerPort: 8081
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
          env:
            - name: "APP_URL"
              value: "https://pg-operator.personal.codemagnifique.com/"
            - name: "OPERATOR_API_URL"
              value: "http://postgres-operator:8080"
            - name: "OPERATOR_CLUSTER_NAME_LABEL"
              value: "postgres-cluster"
            - name: "RESOURCES_VISIBLE"
              value: "False"
            - name: "TARGET_NAMESPACE"
              value: "postgres"
            - name: "TEAMS"
              value: |-
                [
                  "acid"
                ]
            - name: "OPERATOR_UI_CONFIG"
              value: |-
                {
                  "docs_link":"https://postgres-operator.readthedocs.io/en/latest/",
                  "dns_format_string": "{1}-{0}.{2}",
                  "databases_visible": true,
                  "master_load_balancer_visible": true,
                  "nat_gateways_visible": false,
                  "replica_load_balancer_visible": true,
                  "resources_visible": true,
                  "users_visible": true,
                  "cost_ebs": 0.119,
                  "cost_core": 0.0575,
                  "cost_memory": 0.014375,
                  "postgresql_versions": [
                    "12",
                    "11",
                    "10",
                    "9.6",
                    "9.5"
                  ]
                }