apiVersion: "networking.k8s.io/v1beta1"
kind: "Ingress"
metadata:
  name: ingress-postgres-operator-ui
  namespace: postgres
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: "https://auth.personal.codemagnifique.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.personal.codemagnifique.com/oauth2/start?rd=$escaped_request_uri"
  labels:
    name: postgres-operator-ui
spec:
  tls:
  - hosts:
    - pg-operator.personal.codemagnifique.com
    secretName: postgres-codemagnifique-tls
  rules:
  - host: pg-operator.personal.codemagnifique.com
    http:
      paths:
      - path: /
        backend:
          serviceName: "postgres-operator-ui"
          servicePort: 80