apiVersion: v1
kind: ServiceAccount
metadata:
  name: omnibot-user-admin
  namespace: omnibot
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: omnibot-admin
  namespace: omnibot
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: omnibot-admin-binding
  namespace: omnibot
subjects:
  - kind: ServiceAccount
    name: omnibot-user-admin
    namespace: omnibot
roleRef:
  kind: Role
  name: omnibot-admin
  apiGroup: rbac.authorization.k8s.io