apiVersion: v1
kind: Secret
metadata:
  name: omnibot-secrets
  namespace: omnibot
type: Opaque
data:
  discord-token: "{{ omnibot_secrets.discord_token | b64encode }}"
  db-name: "{{ omnibot_secrets.database_name | b64encode }}"
  db-host: "{{ omnibot_secrets.database_host | b64encode }}"
  db-port: "{{ omnibot_secrets.database_port | b64encode }}"
  db-username: "{{ omnibot_secrets.database_username | b64encode }}"
  db-password: "{{ omnibot_secrets.database_password | b64encode }}"
  oxford-app-id: "{{ omnibot_secrets.oxford_app_id | b64encode }}"
  oxford-app-key: "{{ omnibot_secrets.oxford_app_key | b64encode }}"