- name: Deploy Scaleway secrets
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'secrets.yml') }}"

- name: Deploy VolumeSnapshotClasses CRD
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'crd.yml') }}"

- name: Deploy Scaleway driver
  become: yes
  become_user: "{{ system_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'driver.yml') }}"