- name: Make sure python and pip are installed
  become: yes
  apt:
    name:
      - python3
      - python3-pip

- name: Install openshift
  become: yes
  become_user: "{{ system_user }}"
  pip:
    name: openshift