- name: Update sshguard whitelist
  become: yes
  lineinfile:
    dest: /etc/sshguard/whitelist
    regexp: "^{{ item }}"
    line: "{{ item }}"
    state: present
  with_items: "{{ sshguard_whitelist }}"
