apiVersion: v1
data:
  init.userid: "{{ mongodb_secrets.username | b64encode }}"
  init.password: "{{ mongodb_secrets.password | b64encode }}"
kind: Secret
metadata:
  name: mongo-init-credentials
  namespace: "{{ mongodb.namespace }}"
type: Opaque
---
apiVersion: v1
data:
  # Has to be base64-encoded twice
  mongodb-keyfile: "{{ mongodb_secrets.keyfile | b64encode | b64encode }}"
kind: Secret
metadata:
  name: mongo-key
  namespace: "{{ mongodb.namespace }}"
type: Opaque