apiVersion: v1
kind: Service
metadata:
  namespace: "{{ mongodb.namespace }}"
  name: mongo-db
  labels:
    name: mongo-db
spec:
 ports:
 - port: 27017
   targetPort: 27017
 clusterIP: None
 selector:
   app: mongo
