- name: Disable SWAP
  become: yes
  shell: swapoff -a

- name: Disable SWAP in fstab
  become: yes
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'