- name: Obtain cluster join command
  become: yes
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  delegate_to: "{{ groups['masters'][0] }}"

- name: Set join command to a fact
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join cluster
  become: yes
  shell: "{{ join_command }}"
