apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-discord-rss
  namespace: {{ drss.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - {{ drss.hostname }}
      secretName: discord-rss-omnireborn-tls
  rules:
  - host: {{ drss.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: discord-rss-web
          servicePort: 8081