apiVersion: v1
kind: Secret
metadata:
  name: drss-secrets
  namespace: "{{ drss.namespace }}"
type: Opaque
data:
  discord-token: "{{ drss_secrets.discord_token | b64encode }}"
  discord-client-id: "{{ drss_secrets.discord_client_id | b64encode }}"
  discord-client-secret: "{{ drss_secrets.discord_client_secret | b64encode }}"